### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by sngo25** [issy123/agario-protocol#2]
Can you share us on how you do reverse engineering to get these protocol specification? For example, which tools do you use? This is important because other (many) people can help maintaining the specficiation.

**Comment by issy123** [comment]
Hi! 

I mostly got this information from others who are trying to decode it but the easiest way to reverse engineer the protocol is by replacing the window.WebSocket. So you can listen to what gets send and received.  Works for all websites using websockets.

Here is the code:

http://pastebin.com/Ykx4LRDh

**Comment by sngo25** [comment]
Great! I'm going to use this in https://github.com/SNSA/agario-code

**Comment by issy123** [comment]
Feel free to contribute! At the same time this helps you out too
