### ISSUE TITLE
First two authorisation tokens

### ISSUE THREAD

**Issue by wishstorage** [issy123/agario-protocol#3]
I got another auth tokens

new Int8Array([-2,6,0,0,0]);
new Int8Array([-1,-59,42,64,54]);

Can be the second frame different!?

**Comment by issy123** [comment]
Maybe the tokens are composed of the game server ip and port? 
Are these different every other server? 

If not, this could also be time based auth tokens. Which expires each x time maybe

**Comment by issy123** [comment]
Are these different every other server?

**Comment by sngo25** [comment]
The first one is always the same but the second one depends on agario.core.js version (look at the last number at the end of the file)

**Comment by terjanq** [comment]
@heroandtn3 

Are you working on repair agario?

**Comment by wishstorage** [comment]
Ok, may be so... Now I have this:
new Int8Array([-2,6,0,0,0]);
new Int8Array([-1,-33,-8,119,-40]);

At the end of agario.core.js number is 40. Is it the last of array!?
So 
-1 - I suppose it is constant
-33 - ???
-8 - ???
119 - ???
-40 - the last number at the end of the agario.core.js file

**Comment by sngo25** [comment]
> -40 - the last number at the end of the agario.core.js file

Actually not, it's just a random.

**Comment by wishstorage** [comment]
I record websocket traffic several times on different rooms, different countries, different ip (
through proxy), but this packet (new Int8Array([-1,-33,-8,119,-40])) is the same

**Comment by wishstorage** [comment]
I might have a look on this file during its changing

**Comment by wishstorage** [comment]
Today
new Int8Array([-2,6,0,0,0]);
new Int8Array([-1,-6,112,37,42]);
